// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxhwjCdRYlcX2L6nffb2Z_po8mvQUZ0OA',
    appId: '1:25776003293:web:3f952ace29d57abbc1a334',
    messagingSenderId: '25776003293',
    projectId: 'whats-app-370d7',
    authDomain: 'whats-app-370d7.firebaseapp.com',
    storageBucket: 'whats-app-370d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0kXOQPgPBUS9NypxLnttqWK6U847d5Wo',
    appId: '1:25776003293:android:8e49f5c19e008456c1a334',
    messagingSenderId: '25776003293',
    projectId: 'whats-app-370d7',
    storageBucket: 'whats-app-370d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKlaOy6MA_a46TZs98qglo27eGyrJHleY',
    appId: '1:25776003293:ios:c7c7c7ff0a27eb3ac1a334',
    messagingSenderId: '25776003293',
    projectId: 'whats-app-370d7',
    storageBucket: 'whats-app-370d7.appspot.com',
    iosClientId: '25776003293-lg2kabk4s09f4dkn29e4v5decdnm6q5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
